title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

# External navigation links
nav_external_links:
  - title: Github 仓库
    url: https://github.com/ZzNoah/cairn-cn/
    hide_icon: false
    opens_in_new_tab: true
  - title: Discord 频道
    url: https://discord.gg/K3dwaMap5X
    hide_icon: false
    opens_in_new_tab: true
  - title: 2e 测试材料
    url: https://cairnrpg.com/wip/2e/
    hide_icon: false
    opens_in_new_tab: true
  - title: 订阅新闻
    url: https://news.cairnrpg.com
    hide_icon: false
    opens_in_new_tab: true
    
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
